### ISSUE TITLE
Drag not working on mobile devices with touch display

### ISSUE THREAD

**Issue by sander-v-bergen** [angular-dragdrop/angular-dragdrop#114]

**Comment by ganarajpr** [comment]
This component does not ( yet ) support mobile devices.

**Comment by bmenzel** [comment]
What does 'not (yet)' mean? ;-)
Are there plans to make it work for mobile devices? If so, can you already tell when probably (estimate)?

Background:
I have implemented your library in a project which now needs to be made available for mobile devices and i am thinking about rewriting it to use some other drag&drop library but i would like to stay with your library as it is the only one supporting channels and validation.

**Comment by zauker** [comment]
No news about touch?
I used this library in a project which now needs to be available for totem devices.

**Comment by ganarajpr** [comment]
@bmenzel and @zauker : I am sorry guys.. but I dont want to give you false hopes. I do not intend to implement any support for mobile devices myself. While having said that, I am open to any pull requests which make that happen ( which is the reason for the 'yet' ;) ) . 

There are alternatives like :

https://github.com/fatlinesofcode/ngDraggable

and 

https://github.com/codef0rmer/angular-dragdrop

which maybe more suitable for those scenarios perhaps ?
