### ISSUE TITLE
possible to drag an item even if ui-draggable="false"

### ISSUE THREAD

**Issue by mjmvisser** [angular-dragdrop/angular-dragdrop#115]
You can still drag and drop items if text is highlighted.

Here's a plunk:

http://plnkr.co/edit/tXGzTXWpDpq0lntk1Rqn

(The only difference from the original is that ui-draggable has been set to "false".)

Click and drag to highlight John, Jack, Mark and Ernie. Now click on one of the names and drag them to the second column.

**Comment by Toilal** [comment]
It's not really the item you drag in this case, it's the text selection that has natural drag&drop capabilities of selected text provided by the browser.

Just try to select any word from my comment, and move it to your navigation bar. It will transfer the selected text data to the URL bar. In chrome, it make a search with this text, in firefox it just paste the text to the URL bar.

Maybe we should disable selection on draggable items, to avoid this issue.
