### ISSUE TITLE
Issue only in IE8 

### ISSUE THREAD

**Issue by nerellamahesh** [angular-dragdrop/angular-dragdrop#123]
I am getting this error only in Internet Explorer 8 , in Chrome and firefox it is working fine.

SCRIPT5022: [$injector:modulerr] http://errors.angularjs.org/1.2.28/$injector/modulerr?p0=kp.mydoctor.empanelment&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.28%2F%24injector%2Fnomod%3Fp0%3Dkp.mydoctor.empanelment

**Comment by ganarajpr** [comment]
This does not seem to be an issue related to this angular module. If it is can you re-open this issue with a plunker or jsfiddle demonstrating this ( by isolating the issue ) ?
