### ISSUE TITLE
Cannot read property 'dropEffect' of undefined - Chrome 43 - Windows 8.1

### ISSUE THREAD

**Issue by kjmeath** [angular-dragdrop/angular-dragdrop#130]
After dropping, Chrome on Windows throws a console error:
TypeError: Cannot read property 'dropEffect; of undefined.

Appears to work fine on mac.

**Comment by kjmeath** [comment]
I fixed this Windows specific chrome bug by changing line 10 from:
if (e.dataTransfer.dropEffect === 'none') {
to
if (e.dataTransfer && e.dataTransfer.dropEffect === 'none') {

**Comment by Toilal** [comment]
Fixed

**Comment by torkelo** [comment]
a new bower release would be nice, latest bower release 1.1.1 is now working :(

**Comment by Toilal** [comment]
Thanks for pointing this out, it's now released as 1.1.2 on npm.

**Comment by torkelo** [comment]
Great :)
