### ISSUE TITLE
To drag we are not able to see which element are dragged in chrome only

### ISSUE THREAD

**Issue by hemantpatil25** [angular-dragdrop/angular-dragdrop#136]
To drag we are not able to see which element are dragged in chrome only.

Please let me know is there any workaround.

**Comment by hemantpatil25** [comment]
Any updates?

**Comment by ganarajpr** [comment]
Can you provide a fiddle with the issue reproduced ?.

**Comment by hemantpatil25** [comment]
Thanks ganaraj for reply.

I have resolved the issue.

**Comment by kresho** [comment]
Great, can you tell us how you resolved it?
