### ISSUE TITLE
How do you get the position of the element when its dropped

### ISSUE THREAD

**Issue by tawanda** [angular-dragdrop/angular-dragdrop#141]
How do you get the position of the element when its dropped i tried `$event.pageX` but it says undefined

`
$scope.onDrop = ($event, $data, array) ->
      array.push $data
      console.log('x position when dropped"event->",$event.pageX,"data->",$event,"array->",array)
      return

`

**Comment by jasny** [comment]
I've added this functionality to this library in my fork. I've added a pull request for it: #142

**Comment by tawanda** [comment]
Awesome
