### ISSUE TITLE
How to style the element during drag

### ISSUE THREAD

**Issue by tristanpendergrass** [angular-dragdrop/angular-dragdrop#145]
I see in the docs how to style the element
 - left behind after you start dragging
 - the dropzone

But I don't see how to style **the element that my mouse cursor is actually hanging onto during the drag**. I tried to find it using the chrome dev tools, but since the "dragged" element disappears the moment I stop dragging to try to use the dev tools I couldn't use them to inspect the dragged element.

How can I access this element (class name, id, or something)?

**Comment by kresho** [comment]
Looking at the directive source code, you can use the drag-image attribute to set some text to be used for the dragged element. It is not documented though, so not sure if it will be supported in the future.

**Comment by ganarajpr** [comment]
It will be supported in the future. We have no plans of removing features that are already part of the library. About the docs: we are undergoing some efforts to revamp the docs but its no-where near ready and any help in that department would be much appreciated. 

Closing this as its a question.
