### ISSUE TITLE
Drop regions

### ISSUE THREAD

**Issue by dstran** [angular-dragdrop/angular-dragdrop#149]
Are there plans to support droppable regions like top, right, bottom, and left on the element similar to the Eclipse IDE?

**Comment by ganarajpr** [comment]
I believe this is slightly out of the domain of what this directive is meant for. This directive does expose the position data - so it can surely be built on top of this. But putting it into this directive is slightly outside the scope of this directive.

**Comment by dstran** [comment]
Thanks for the quick respond. Could you point me to where the directive exposes position data?

**Comment by ganarajpr** [comment]
I believe its part of the event exposed on `onDrag` and `onDrop`.
