### ISSUE TITLE
cannot drag non-browser text into a angular typeahead

### ISSUE THREAD

**Issue by Radu3000** [angular-dragdrop/angular-dragdrop#153]
I have an office app and I would like to drag text items from the office app into angular uib typeahead.

I have followed the getting-started steps and my html looks like:
`<input type="text" ... ui-on-Drop="onDrop($event, $data)" ... >`

I have a corresponding method in my controller and nothing gets logged.  
```
$scope.onDrop = function($even, $data){
console.log("event is: " + JSON.stringify($event));
}

```
- Is that even possible?

Thanks,
Radu

**Comment by ganarajpr** [comment]
You dont need angular dragdrop to accept text into a text field. Text Inputs should take text dragged into them even without using any library.

**Comment by Radu3000** [comment]
Ganaraj,

You are right that by default any html input text accepts drag and drop of text.  However my requirements are more demanding:
- Be able to clear the contents of the input text when drag text enters.  onDragEnter - i believe you don't have such an event yet, right?

Can you please re-open my question?

Thanks,
Radu

**Comment by Radu3000** [comment]
Also i can clear the text with JQuery - but it is a hack - would really want to stay pure angular code.

My hack:
`
<html>
<script>
  function updateSearchTextfield(val) {
    $('#searchfield').val(val);
    var ctrl = $('#searchfield').controller('ngModel');
    ctrl.$setViewValue(val);
  }
</script>
<html>
...
          <input type="text" id="searchfield" class="form-control"
                          ondragenter="updateSearchTextfield('')"
...
</html>
`
