### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetX' of undefined

### ISSUE THREAD

**Issue by CrimsonGlory** [angular-dragdrop/angular-dragdrop#155]
When trying a similar code of the example I get:
Uncaught TypeError: Cannot read property 'offsetX' of undefined
Removing all the ".originalEvent" from the source fixed the issue.

Tested on  Google Chrome 49.0.2623.87 m (Windows)

**Comment by ganarajpr** [comment]
If you fixed the issue could you send in a PR please ?

**Comment by thepercival** [comment]
Code is merged and issue can be closed
