### ISSUE TITLE
Add style for floating dragging item

### ISSUE THREAD

**Issue by pelizza** [angular-dragdrop/angular-dragdrop#168]
It seems there is no possible to add style to the element that keeps floating while performing a drag event. A class is added to the item being dragged ("on-dragging" class), but this item seems to be both the origin one and the "helper" floating.

I'm looking for this configuration to set "cursor: move" for the floating item and also change its border.

http://prntscr.com/c3rk0w

Am I missing something?

Thanks.

**Comment by ganarajpr** [comment]
Its not currently in the documentation , but if you are keep look here :

https://github.com/angular-dragdrop/angular-dragdrop/blob/master/draganddrop.js#L144

**Comment by pelizza** [comment]
Cool, thanks! I'll try it!
