### ISSUE TITLE
ui-on-drop doesn't work with ngRepeat

### ISSUE THREAD

**Issue by msjansen** [angular-dragdrop/angular-dragdrop#169]
If the ui-on-drop is attached to an item within an ngRepeat, it doesn't do anything.

**Comment by erosval** [comment]
+1 same issue.

**Comment by ganarajpr** [comment]
Can you provide an example ( create a jsfiddle or plunk and attach it to the issue please )

**Comment by msjansen** [comment]
If I grab the plunk from the site http://angular-dragdrop.github.io/angular-dragdrop/examples/, then it works (moving the ngDrop inside the list item). But if I try this in my own project, it doesn't.

I see that the plunk is using some (old?) library:
module "ngDragDrop" (plunk)
instead of "ang-drag-drop" (http://angular-dragdrop.github.io/angular-dragdrop/getting-started/)

**Comment by erosval** [comment]
The problem exist only when a use it on my testenvironment and webserver host is something like http://localhost/...
Maybe is a cross-origin XHR problem, so is a non problem...
Tks

**Comment by msjansen** [comment]
Problem was that the function that I passed for ui-on-drop was not in the scope. Maybe an error message if the function is not found would be helpful.
