### ISSUE TITLE
Dragging and dropping to the same container should not fire callbacks

### ISSUE THREAD

**Issue by selvakn** [angular-dragdrop/angular-dragdrop#67]

**Comment by Toilal** [comment]
There are case where it make sense to drag/drop element from/to the same container, for example to reorder the elements of a list using dragdrop, by using the mouse event provided by $event.

With latest master, drop-validate is fixed, and you can validate each possible destination of an element. 

See example in `test.html` and `js/app.js`, there's a check on `$drop.element !== event.srcElement.parentNode` to disable dragdrop to the same container.
