### ISSUE TITLE
on-drag-hover and on-drag-enter classes should be removed upon drop-zone exit

### ISSUE THREAD

**Issue by RavenHursT** [angular-dragdrop/angular-dragdrop#78]
The two classes behave, essentially the same which makes them rather redundant.

The on-drag-hover should behave like it's name suggests and only be present on the dropzone when a draggable element is hovering over it and not be present otherwise.

Not sure how the ui-hover-enter class is utilized, since it's just added upon hover and never leaves until after drop anyway.

**Comment by Toilal** [comment]
If think it's now solved in `master`, feel free to reopen I you still have issues with those classes.
