### ISSUE TITLE
on-drag-hover is instantly removed, if it is nested within another droptarget

### ISSUE THREAD

**Issue by mathielen** [angular-dragdrop/angular-dragdrop#79]
I modified the demo:
http://plnkr.co/edit/ucpyenUIjPR0jNczEaDY?p=preview

Now every li is a drop-zone within the parent ul-drop-zone.

Unfortunately the li-element's on-drag-hover class is instantly removed by the event listener:

```javascript
var deregisterDragHover = $rootScope.$on("ANGULAR_HOVER", function (e, channel) {
    if (isDragChannelAccepted(channel, dropChannel)) {
        element.removeClass(dragHoverClass);
    }
});
```

For what is this necessary anyway?

**Comment by Toilal** [comment]
Should be fixed now.
