### ISSUE TITLE
Input fields are valid drop targets by default

### ISSUE THREAD

**Issue by pjdewitte** [angular-dragdrop/angular-dragdrop#93]
When dragging a ui-draggable over a text input, the text input is a valid drop target unless explicitly prevented by using ui-on-drop and its options. When dropped, the drag data json is added to the text input value. This is easily demonstrated by adding a text input field to the live demo.

This behaviour occurs at least in Chrome and Firefox.

In most use cases dropping a JSON string in a text field is undesirable. Perhaps the use case "drop string in text input" should be supported with an option for it, but it shouldn't be the default.

We solved the problem with:

```
-                        e.dataTransfer.setData("Text", sendData);
+                        e.dataTransfer.setData("angular-dragdrop", sendData);
```

and 

```
-                    var sendData = e.dataTransfer.getData("Text");
+                    var sendData = e.dataTransfer.getData("angular-dragdrop");
```

Should I submit a pull request with these changes?

**Comment by kjmeath** [comment]
I am using v1.1.0 and having this same issue, on chrome, mac os.
