### ISSUE TITLE
e.dataTransfer.setData("dataToSend", sendData); breaks IE

### ISSUE THREAD

**Issue by chuang88** [angular-dragdrop/angular-dragdrop#96]
Reason:

http://msdn.microsoft.com/en-us/library/ie/ms536744(v=vs.85).aspx

I think we need to do a try catch there b/c:

https://github.com/ganarajpr/angular-dragdrop/issues/56

**Comment by xxneon** [comment]
The first parmeter for setData / getData is a string to tell what format you want to store the data as.  It seems that the only two valid values are 'text' or 'url'

Line 115: e.dataTransfer.setData("text", sendData);
...
Line 214: e.dataTransfer.getData("text");

If you update these lines. Drag and Drop in IE works again.

**Comment by Schweigi** [comment]
I can confirm this issue exists on IE11. So either revert back to `Text` or use a try-catch approach. In my opinion it would make more sense to break it for Chrome on Linux than break it for all IE users.

Regarding #74: 
Can somebody test with Chrome on Linux as version 41 is already out. I tested with Chrome v41 on Windows and Mac and those versions both work fine with the `Text` format.

**Comment by Toilal** [comment]
Fixed with https://github.com/angular-dragdrop/angular-dragdrop/commit/b8ecd15aca9b78ceff62b9c40ac28feddf09b30d
